---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: grafana-authentik
  namespace: monitoring
spec:
  encryptedData:
    client_secret: AgCd4ZC2Mgu0DJY0yQJe4kU07H3MeacQSKLh5oLdW90xSkF+yTF0ThS4iKybFICcW819iHxbYWYeKvKsXtcicsGYZm8FOo15+4VmnJ2st9aIPmYEPuG/HO52URNdHAkhkuDLbiiOQNK3Wt7cR/jfkLM0WYZbIAo/ffkC1jLenmCjPljC/2IdDGqZt2GdWWz9UrrWpGH89IfknQi7HM2C0qXJTl6ZG+SXYdczc8DNdBl0Xu+INVu0k/JF9OzZZQqSPY38btcGVj8BVwSwZi1j6xlRFSItHVL4W8lwTuOKAE8PyRq3BMNrj4nYWbuou19n3+6C0GorcUmZ98R7/7kX9UNdkntqyNMw/pI4/fmFlRYkuekhkzwxB8v9BZx9usPpO6ps96emiBMcYpIy/lqx/guStRGuH01lEW6ydYVFXTUf6Lw++XnEHqo3cFinJIMtVCI1Si6XWQ/0Rn2de1ZP1vP8MM0qmdsmb+Mc9zdjZKaRq2wvbF0KfyHTGnEkCMvhhm6mAA7CaKEDqcVe7h4JeWci+sbCEEheuND/CnlGMNhbwh7W17mntn/V0JNGFKkywBMeHPFNoqc3AyFayH18Sgm6kM4qFJhnJ5+nIhFsfpP/Lxvsp9QC2rV1tnzoXa61dSHMTIK2dJxez0s60KpOuZdhoMA6UM7NGkGiduy/7h8au1REqiuGaE09WFze3dCWABLJ449URUt5Y+9m1/GazZV1QAGzkwyF5KyLW9OUGloZkxn9/3ycSuZjVQuYfX9tHLmTIW5nhwMk6wIvTpBaeJJd5FeMtZVHrOVR1FpJK5o0hILVRP7TVe0kcmNvM0LTeplvhYD9gHXNwLBxGh3vqbY1sY3A5D5bMtApDpKsLHrGGg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: grafana-authentik
      namespace: monitoring
    type: Opaque
