apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-applications
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/luciocarvalhojr/k8s-home-lab.git
    path: argocd/
    targetRevision: main
    directory:
      recurse: true
      exclude: 'values.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: {}