apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-config
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  project: default
  source:
    repoURL: https://github.com/luciocarvalhojr/k8s-home-lab.git
    path: infrastructure/external-dns/
    targetRevision: main
  syncPolicy:
    automated: {}