apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-api-config
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  project: default
  source:
    repoURL: https://github.com/luciocarvalhojr/k8s-home-lab.git
    path: k8s-apiserver-oidc/
    targetRevision: main
  syncPolicy:
    automated: {}