apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observatory-auth-svc-config
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/luciocarvalhojr/k8s-home-lab.git
    targetRevision: main
    path: observatory/
    directory:
      recurse: false
      exclude: '*-values.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: observatory
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
