global:
  domain: argocd.capihome.xyz

server:
  service:
    type: ClusterIP

configs:
  cm:
    oidc.config: |
      name: OIDC
      issuer: https://auth.capihome.xyz/application/o/argodc/
      clientID: argodc
      clientSecret: ZyAzxpXlRKAYBIkItkOpEHxY9SMvA4qg55GLRqKIt4UatFnRUXIhmUxOUmVhPkAAhXwsxM5awKdVRmKnTqVV89PTpE94dh90hM1afG3PmQ5vxYu5Yg6dwA53WBDIlc0l
      enableUserInfoGroups: true
      requestedScopes: ["openid", "profile", "email", "groups"]
  rbac:
    policy.default: role:readonly    # default role for all authenticated users
    policy.csv: |
      # Admins group from Authentik gets full access
      g, argocd-admins, role:admin
  params:
    server.insecure: true

extraObjects:
  # -------------------------
  # Certificate (cert-manager)
  # -------------------------
  - apiVersion: cert-manager.io/v1
    kind: Certificate
    metadata:
      name: wildcard-capihome-xyz
      namespace: argocd
    spec:
      secretName: wildcard-capihome-xyz-tls
      issuerRef:
        name: letsencrypt-cloudflare
        kind: ClusterIssuer
      dnsNames:
        - "*.capihome.xyz"
        - "capihome.xyz"

  # -------------------------
  # Traefik IngressRoute
  # -------------------------
  - apiVersion: traefik.io/v1alpha1
    kind: IngressRoute
    metadata:
      name: argocd-server
      namespace: argocd
      annotations:
        external-dns.alpha.kubernetes.io/hostname: argocd.capihome.xyz
        # external-dns.alpha.kubernetes.io/target: 192.168.0.161
    spec:
      entryPoints:
        - websecure
      routes:
        - kind: Rule
          match: Host(`argocd.capihome.xyz`)
          priority: 10
          services:
            - name: argocd-server
              port: 80
        - kind: Rule
          match: Host(`argocd.capihome.xyz`) && Header(`Content-Type`, `application/grpc`)
          priority: 11
          services:
            - name: argocd-server
              port: 80
              scheme: h2c
      tls:
        secretName: wildcard-capihome-xyz-tls