config:
  oidc:
    clientID: "kube-apiserver"
    clientSecret: "qiylOjjsXwH9M5xmvoiC9Q67oNQyanIB3OLRWcMsQ2hsjJsv4rFzahY3SYezLvnVQcjxiKbVGubjY9Mwg4urHuSmcWue4BPq6mpFp4yj9RO2aW3fhUjvji0ALjgs5s1N"
    issuerURL: "https://auth.capihome.xyz/application/o/kube-apiserver/"
    scopes: "openid,profile,email,groups"
    # meUserInfoURL: "https://my-headlamp.capihome.xyz/oauth2/userinfo"
  extraArgs:
    - --oidc-skip-tls-verify
    - --insecure-ssl
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare
    external-dns.alpha.kubernetes.io/hostname: my-headlamp.capihome.xyz
  labels:
    app.kubernetes.io/part-of: traefik
    environment: prod
  hosts:
    - host: my-headlamp.capihome.xyz
      paths:
        - path: /
          type: ImplementationSpecific
  tls:
    - secretName: wildcard-capihome-xyz-tls
      hosts:
        - my-headlamp.capihome.xyz
