replicaCount: 1

image:
  repository: ghcr.io/luciocarvalhojr/observatory-auth-svc
  pullPolicy: IfNotPresent
  tag: "1.5.0"                    # overridden by appVersion in Chart.yaml

service:
  type: ClusterIP
  port: 8081

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare
    external-dns.alpha.kubernetes.io/hostname: observatory-auth.capihome.xyz
  hosts:
    - host: observatory-auth.capihome.xyz
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - observatory-auth.capihome.xyz
      secretName: wildcard-capihome-xyz-tls


  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70

env:
  PORT: "8081"
  ENV: "production"
  JWT_ACCESS_TTL: "15m"
  OIDC_ISSUER: "https://auth.capihome.xyz/application/o/observatory-auth-svc/"            # set in environment values file
  OIDC_CLIENT_ID: "observatory-auth-svc"         # set in environment values file
  OIDC_REDIRECT_URL: "https://observatory-auth.capihome.xyz/auth/callback"      # set in environment values file
  OTLP_ENDPOINT: "http://jaeger-collector.observability:4318"

# SealedSecret owns auth-svc-secret — Helm will not create it
externalSecret: true
secrets: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 65532
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop: [ALL]

livenessProbe:
  httpGet:
    path: /healthz
    port: 8081
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /readyz
    port: 8081
  initialDelaySeconds: 5
  periodSeconds: 10
