---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: db-credentials
spec:
  encryptedData:
    password: AgBGcmZBnrafl4PMxrZBs14dIlVBVaQhG3hdrz6bsqQpG9+6tTgq5SepcHo1PHmxdWrt+Vk8jAqMbG2YFjdfive/dvyFMEnpGHOPUQRQYOJIv+2x7V4ZIcj94XrCeQAxqh7dMyBL/jWzvNEQ8znEKr5XSg7Xa1akwnNUFOHkaK4LLFoKv02lHgIPH0pAi0V5a6uNL9pHxuOvzMo7UBVvhoGT5kwVVswz88/cXs3gB+ZC3ungfI+TQcDPqe38J+OHhUYj1gOfw6OR33mr1iSdX8Nfe80oeIk8qjpT8iIQrX+hP6fuFUqxUgr4BxXTRDXxV56rK76BPIkiFmemAFHMGX0jQuIiH9qIL/H67tWPPnrk0cFE0xndhWuGjlHq1TSV7Rki5DmjIXEzMX3HOqOcvZCU6F/8yNhgD8zINGbgkg0U/O7pWNn8FOpM4hlMCWVvVJKsYuy69xB7Aav9DnSFVQW46bNncdv2HQaP1sofwQPItzK4LrZqbLaXcyYfRiVVPE9Pp7vaLF5rn1cqUjUGfLk9a6xG2ObMmHRJS7STO6PsMUR3gIE09FqEfz3Z2iTvIbBnWcs36M+zCJoaOA+W0pH9FikgrWzMnagmACjXMYXSC2hjzXzd+U0/zIbIOS438WVT31WlWb4a+ocTMqV9evQisoC9QC9oGKwtOoL9z+O3eWaFUcbfTsir/UgPLmh4bGNJuA2sayUH
    username: AgC23MRO3/ljs2ncAYIhKbBjFfn7x/O5Teav9fZlr6PiFqJXeWqNiDckCJRR7yK2tlVSz+K5eg2jMAWEbH0NllN1tt6/ppvIQ18VgT8DnbyyXAs0c1JEopTMPWqfESribGVzFqnCZ5CF8y3RcAmoQhVwiYf7yy8R/0I3I2AxPjDOE0vK3hM+BCdZy+L3pEKw/Hnm7e6as8l8a5MYI8+rpkY8kzgVXe1ZKKNr++B4VtPBGHB+nneCW7rjJi5qrTggJzFUwS5fN55GoluAwIdXS9VEHLTQGQgb9BO240yF0N8DxwnnZ8RiMetmjc3sgs9lCy80WTWjfJ7iwNWjoincPqwKDsYPpxfofolEauWWluFSlSdcmvN8CjFCFfPiALtfYbYtk8dUJCD2jlz8CBUHrk09356h/zDR3CNv+scUr/Y8q4nk8IkNnO6+UTfZh/B/cVwX3A3ng5M/HpyHwQexdMV4YpWEswIgbPCo5oCqEmvhHjDF4UWLXuM6xeSMbxowCP5YxhSEc3ROqfQAaX5WGWslvuPTzvSvzTcpuZxlrFRn7DxVCGTkcFouNjr4QYmfI2FlhJOF3NFbmCeso4Vx0CyGM3SBZVxBOjPo+K5qpykTMQQ8XzPM6fdyi3YJs3/cL2iDLayzU/97UbSdr8MiqTg7JuPyy5QudvMzb1Kv705gxWpi18YvMkgHYTkFOtAhaosqjcDGLQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: db-credentials
