---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-secrets
  namespace: authentik
spec:
  encryptedData:
    AUTHENTIK_SECRET_KEY: "AgCoA44gZC46sfDBfQJw0mkDyv8IX5uweSn+E3WuV+eSsh9G9XoblN1U/x+KUdBkDsjxggvN06cJ+0qvR+F781PFNTmb7smdJrNDdmL+hNfrAhGIdWNqOLL3CeWTHknWiZkcpURj8qbVgSDsIJArBM3L8sq1+1C9iLUmyoux+o5lLEC5m5TIq5ls8tdJstbeyZ1u7Uy4MoJsnio933FFS9MtiDbeFVkFWshLdiKx2vYkQstfhvNEFGBsQXSj4DykVb2GonVfcWDmgANIlcRzAkxBWIJzZH5mI9XRiAIgRTASuR285L1XfyOnqIrpFGJKgTutNZP1qBARG9ekzJUB99OwLfFBpd0076YrKP33AjQCqThBSXmKvM3Zpif149Z7U5uE/lMgDbYem9uTIhSoF2/8AQYyBPViDGxEdg6nJJ4SBHih/aah7xeCWqRmMrRHm1+yuweolH04IHMRUYrz6HJEW7qT/rhV1w0MeQcKFTRznrQ9j7yBXI712ajP0mMFqAqxqGSfMahCC96qqGyD0OBvmXhhnCvajvBoRei9Qf8sOYNSC4p+wqVOlFIqnYN85rCcAIqUWime9KKpnqnt4gkV7SD7lOTExgqEWIcYz1mkQycdPpIxrcL2S7dlkhU1mMoYL2cIAKqItIp8aw0vM/USV92VslGogZuRul7rdfJbHWIp7BtalOhdXh5MytFuBpfgvopMOVFFPJvGi/Ub9vsRVxUA46O4HPmh/KE="
    AUTHENTIK_POSTGRESQL__PASSWORD: "AgBjygeJX7osIGr8d2RUzrFaq9r1w0mqWj1wCyhuNgLD0H7/ZqL7D7Bi+cUcyAw1vEouYLlNGj2TSS3t+u6V5RXkZ5DnCmJLtKe/z5B3dnpaz0dqw8km5Ruvu82axbdMmC9whPkO9duVw2sBErqIJiw281B1s/rb44dc0YJl+SEVvvG+ZYLwrykQtspIUw3eR8/wwMW+iDto+iFgjz0YsmkBfLJp+JvWXS03PdC7qiKjjCM4h25oZmZoyyPJx59yJsYFHXMyse+LG4niZx9Y0uFf1BLiDvMAk4corZO5/Lkwe4TVd6FmtKgKYTz9t1guZpquSfn+08aApFSv+BqfS3eYFfuEbklnNfX5UMcG8QHCW2LuNFmK/S/JctcIeJgba+f6hmRUpsjg4zl0tWD96hTUVyzbRmuHjCz0t8m1m67diBH5at6Z+6vW8PLaW78rXiLSa9+nGv2h8Gkb+i75KOIqCaH1Hr1Mw9s1en36YsgaE7NnD9lMWNs1miKuRO8pArusIUxkypYqCmuGCenSq6SYb+9V7ga1AOfx9JfDp0Gxs/JwDXOwgWm5TE8t3sF/CEuun08dF16kcAibk4Ckp/O/e/14gSdBmDyqBCawyexxkhmI97lxGeNWcfrg5eWmWs/9HeQKPcBu71HncKm5xQkuL7XAOhlnNKe9f/eqSSkG5yHYmUNMaoYWjb5xm5/YdDx79I+nGZDi1zwe5dW0A/SEuYvKclZC6l+YLVCIMKOJbKuJ"
  template:
    metadata:
      name: authentik-secrets
      namespace: authentik
    type: Opaque
