global:
  postgresql:
    auth:
      existingSecret: "authentik-secrets"
      secretKeys:
        userPasswordKey: "AUTHENTIK_POSTGRESQL__PASSWORD"
      username: authentik
      database: authentik


authentik:
  existingSecret:
    secretName: "authentik-secrets"
  # This sends anonymous usage-data, stack traces on errors and
  # performance data to sentry.io, and is fully opt-in
  error_reporting:
    enabled: true

server:
  env:
    - name: AUTHENTIK_POSTGRESQL__HOST
      value: authentik-postgresql
    - name: AUTHENTIK_POSTGRESQL__NAME
      value: authentik
    - name: AUTHENTIK_POSTGRESQL__USER
      value: authentik
    - name: AUTHENTIK_POSTGRESQL__PORT
      value: "5432"
    - name: AUTHENTIK_POSTGRESQL__PASSWORD
      valueFrom:
        secretKeyRef:
          name: authentik-secrets
          key: AUTHENTIK_POSTGRESQL__PASSWORD
  ingress:
    # Specify kubernetes ingress controller class name
    ingressClassName: traefik
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-cloudflare
      external-dns.alpha.kubernetes.io/hostname: auth.capihome.xyz
    hosts:
      - auth.capihome.xyz
    tls:
      - hosts:
          - auth.capihome.xyz
        secretName: wildcard-capihome-xyz-tls

worker:
  env:
    - name: AUTHENTIK_POSTGRESQL__HOST
      value: authentik-postgresql
    - name: AUTHENTIK_POSTGRESQL__NAME
      value: authentik
    - name: AUTHENTIK_POSTGRESQL__USER
      value: authentik
    - name: AUTHENTIK_POSTGRESQL__PORT
      value: "5432"
    - name: AUTHENTIK_POSTGRESQL__PASSWORD
      valueFrom:
        secretKeyRef:
          name: authentik-secrets
          key: AUTHENTIK_POSTGRESQL__PASSWORD
postgresql:
  enabled: true
  primary:
    persistence:
      enabled: true
      storageClass: nfs-rwx
      accessModes:
        - ReadWriteMany
      size: 8Gi

redis:
  enabled: true
