---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: cloudflare-api-key
  namespace: kube-system
spec:
  encryptedData:
    apikey: AgC6Z+I3iTSMiynnfwTlE9/eU88pLkn/c4b8J3lEGwpH9+4TeREIWaGai3W8I7cmjq7ZQo/cbNOQ/a1t855wzyZOtwi/M5b6A0EOvQdwDbI+wHRUJOM3SqbBwqQiUeFC46W5Th2zjodN3UQVFnJ2hJvZURAqjS9ZqbFmwypJiU5O+rlqtvGuDzidUs05lwxPmi3TCKNGxswisjToUqI1BcXydUp6REInqZd017QmE0rDYP+ldRBKOVybjJ/HI8vTaMw/azj1kLpW0XB+it1CKbmSwlbWuPAet6HEWKmprv7s3owpB7+xVHCzF86sAdgBUDHQQ4sqRzHbg8ujfNS7b+K7QAIv27ZsszuWe2ajvdoA2U/BVXMcjSW0t6MahMGzNCtVMbN1BU8+DXQXIW/Q7BiKO58V3kKwfYMhj8Su/S99Q0C85UPUiS9WB56TsuiCOBig8CoirUrQJnFqHp40E/pV6NGfJNnVYFJRl4EkzgZJb8oY8v0RRXI5/9Nir+3AmhntJ8fUiWs4o+hwq7TJGCjCXGGJ2zAfCuAZHa2GWRQtIPN/U655ISS2w2PMSxprBw1tvexeL7d6Qx/dUK6OGIX6nRNoBJ9CZfrtjx/Z1SSjUqCpF+uZjpNhBPRnfx+pMTazg8oKjZH6zSmlSZQtC4sbBhYN6Lxk45JlLe4F565wtMnpi3NdeCbbQvjdMZeDgJ2E8150Kz1Ccu1t8I2Y0HQPr5jHRmK9+HeY0p43kimU2zOz1LyAVgpz
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: cloudflare-api-key
      namespace: kube-system
    type: Opaque
