---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAB/Jkryf2kHZUhjOzRYnCtBt3LFEZS4ixmi8wLbI3BSKyT+8gPkepQYGx/afuiKz6TQYCf0sJ5Usctng7oOshrCwjNBM28GIJrfexVG2JM7H4Z/8CHAmauvdMybPUTT56FUx2ZgrnFJpPRYBY2/iegYKr4hZCnexB5t+P1mXgT4Fqbb9f69jTO/3iiEUL8TYZjsrEZGlBhwW0OkxkvW3pWVnTt6V5y8gJDOmh+eYAIBNDcezcAsiaHi+9VedH8vZAnXdTr/dJzb66Tj9bKvK20XA4TT711eQYfDSz8IbcOMXxu0F1BMk+dmT0MBz28jelqQcGYbtY3veJMjy8Tgc0cR3h1h5hqRUSQzwE8Kazoih3xDwipmO4ts9osm79fbZCUMEv+7wqWtYw3b7hW8Nqmz3uqRZU7tGJUCfFRKna0O3TVDUgr8IuYsj/jNSRgobqA7bqT2IQxXwmmEwBssE30lylCF6lz67+7fG+sG81KU+VvNB2N3eyHND2rI+AdODwzT0D373XwdhI1TmKmGsACx4pGGiuHtOSOkAptnWXr1pVlVoZ9BUmJ8nzHBTF9JGBBtURMD3eu6hHseMsJLQIiuMa+taT6deRVo557KTCmvqZlTmUz4WZ4s3Ymw7qIoJMJZnKICFq6ihToSDJthbzFlIIZxrq8HGF0gMb6p7dwJtUuXZVfEC25+W4pjzXmIHQ77lG2TK1vr32HPL5uc7k2QUfwzt1BPF5LxYuutEohmlpj+i8nLHqc
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
